# Generated by Django 5.2.12 on 2026-03-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_user_search_vector'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_organiz_af0d8d_idx',
            old_name='audit_logs_organiz_created_7a8a8a_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='items_organiz_2c18ff_idx',
            old_name='items_organiz_created_8c8e8e_idx',
        ),
        migrations.RenameIndex(
            model_name='membership',
            new_name='memberships_organiz_3da8e2_idx',
            old_name='memberships_organiz_9b0b0d_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
